package com.harmony.test.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://www.harmony.com/test/hi")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://www.harmony.com/test/hi", className = "com.harmony.test.ws.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://www.harmony.com/test/hi", className = "com.harmony.test.ws.SayHiResponse")
    public String sayHi(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
