CREATE TABLE UMBRELLA_TRIGGER(
    TRIGGERCODE VARCHAR2(50) PRIMARY KEY,
    YEARS VARCHAR2(10),
    MONTHS VARCHAR2(10),
    DAYOFMONTH VARCHAR2(10),
    DAYOFWEEK VARCHAR2(10),
    HOURS VARCHAR2(10),
    MINUTES VARCHAR2(10),
    SECONDS VARCHAR2(10),
    DELAY INTEGER,
    DESCRIPTION VARCHAR2(500)
);