/*
 * 监控视图结果表
 */
create table UMBRELLA_MONITOR_GRAPH (id bigint generated by default as identity, argument varchar(255), errorMessage varchar(255), graphType varchar(255), level varchar(255), module varchar(255), operator varchar(255), requestTime timestamp, resource varchar(255), responseTime timestamp, result varchar(255), primary key (id))
