package com.harmony.test.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-27T21:04:01.974+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "HelloService", 
                  wsdlLocation = "http://localhost:8080/hi?wsdl",
                  targetNamespace = "http://www.harmony.com/test/hi") 
public class HelloService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.harmony.com/test/hi", "HelloService");
    public final static QName HelloWebServicePort = new QName("http://www.harmony.com/test/hi", "HelloWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/hi?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/hi?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloWebServicePort")
    public HelloService getHelloWebServicePort() {
        return super.getPort(HelloWebServicePort, HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloWebServicePort")
    public HelloService getHelloWebServicePort(WebServiceFeature... features) {
        return super.getPort(HelloWebServicePort, HelloService.class, features);
    }

}
