package com.harmony.umbrella.example.ws.wsdl2java;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2015-10-16T15:47:43.247+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://www.harmony.com/srm/test/user", name = "UserServiceBean")
public interface UserServiceBean {

    @WebResult(name = "result", targetNamespace = "")
    @Action(input = "http://www.harmony.com/srm/test/user/UserServiceBean/saveOrUpdateUserRequest", output = "http://www.harmony.com/srm/test/user/UserServiceBean/saveOrUpdateUserResponse")
    @RequestWrapper(localName = "saveOrUpdateUser", targetNamespace = "http://www.harmony.com/srm/test/user", className = "com.harmony.umbrella.example.ws.wsdl2java.SaveOrUpdateUser")
    @WebMethod
    @ResponseWrapper(localName = "saveOrUpdateUserResponse", targetNamespace = "http://www.harmony.com/srm/test/user", className = "com.harmony.umbrella.example.ws.wsdl2java.SaveOrUpdateUserResponse")
    public com.harmony.umbrella.example.ws.wsdl2java.Message saveOrUpdateUser(
        @WebParam(name = "users", targetNamespace = "")
        java.util.List<com.harmony.umbrella.example.ws.wsdl2java.User> users
    );
}
