package com.harmony.umbrella.example.proxy;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.0.0 2015-10-16T15:47:43.247+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://www.harmony.com/srm/test/user", name = "UserServiceBean")
public interface UserServiceBean {

    @WebMethod
    @WebResult(name = "result")
    public Message saveOrUpdateUser(@WebParam(name = "users") List<User> users);
}
