CREATE TABLE TEST_LOGMESSAGE
  (
     LOGID            VARCHAR(200),
     MODULE           VARCHAR(200),
     ACTION           VARCHAR(200),
     KEY              VARCHAR(200),
     LEVELNAME        VARCHAR(200),
     MESSAGE          CLOB,
     RESULT           VARCHAR(200),
     CREATETIME       DATE,
     REQUESTTIME      DATE,
     RESPONSETIME     DATE,
     EXCEPTIONMESSAGE CLOB,
     OPERATORID       VARCHAR(200),
     OPERATORHOST     VARCHAR(200),
     OPERATORNAME     VARCHAR(200),
     LOGTYPE          VARCHAR(200),
     STACKLOCATION    VARCHAR(200),
     THREADNAME       VARCHAR(200),
     CONTEXT          VARCHAR(1000)
  ); 
